---
# tasks file for nodejs

- name: Include distribution specific variables
  include_vars: "{{ ansible_distribution }}.yml"
  tags: nodejs

- include: CentOS.yml
  when: ansible_distribution == "CentOS"
  tags: nodejs

- include: Ubuntu.yml
  when: ansible_distribution == "Ubuntu"
  tags: nodejs
