---
# tasks file for nodejs (Ubuntu specific)

- name: Install Node.js dependencies
  apt: name={{ item }} state=present update_cache=yes cache_valid_time=3600
  with_items: nodejs_packages
  tags: nodejs
