---
# tasks file for nodejs (Ubuntu specific)

- name: Add NodeSource APT key
  apt_key: >
    url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state=present
  tags: nodejs

- name: Add NodeSource APT repository v0.10
  apt_repository: >
    repo='deb https://deb.nodesource.com/node_0.10 trusty main'
    state=present
  tags: nodejs

- name: Add NodeSource APT repository v0.12
  apt_repository: >
    repo='deb https://deb.nodesource.com/node_0.12 trusty main'
    state=present
  tags: nodejs

- name: Install Node.js packages
  apt: >
    name={{ item }}
    state=present
    force=yes
    update_cache=yes
    cache_valid_time=3600
  with_items: nodejs_packages
  tags: nodejs
